# Generated by Django 2.0.5 on 2019-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_auto_20190925_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('World Cup', 'World Cup'), ('Other', 'Other')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
