# Generated by Django 2.0.5 on 2019-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0005_auto_20190925_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
