# Generated by Django 2.0.5 on 2019-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0006_match_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
