# Generated by Django 2.0.5 on 2019-09-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0008_auto_20190925_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
    ]
