# Generated by Django 2.0.5 on 2019-09-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0009_remove_player_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('wicket', models.IntegerField(default=0)),
                ('over', models.FloatField(default=0.0)),
                ('fifty', models.IntegerField(default=0)),
                ('hundred', models.IntegerField(default=0)),
                ('meadan_over', models.FloatField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('man_of_match', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('out', 'Out'), ('notout', 'Not Out'), ('notplayed', 'Not Played')], max_length=10)),
            ],
            options={
                'db_table': 'score_card_player',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='image_uri',
            field=models.ImageField(upload_to='image_user/'),
        ),
        migrations.AddField(
            model_name='playerscorecard',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='cricketapp.Player'),
        ),
        migrations.AddField(
            model_name='playerscorecard',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player', to='cricketapp.Inning'),
        ),
    ]
