# Generated by Django 2.0.5 on 2019-09-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0010_auto_20190925_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscorecard',
            old_name='player_id',
            new_name='player',
        ),
    ]
