# Generated by Django 2.0.5 on 2019-09-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0012_auto_20190925_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscorecard',
            old_name='score',
            new_name='inning',
        ),
    ]
