# Generated by Django 2.0.5 on 2019-09-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0013_auto_20190925_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player', to='cricketapp.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to='cricketapp.Player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team', to='cricketapp.Team')),
            ],
            options={
                'db_table': 'match_player_detail',
            },
        ),
        migrations.RemoveField(
            model_name='inning',
            name='match',
        ),
        migrations.RemoveField(
            model_name='inning',
            name='team',
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='inning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_inning', to='cricketapp.Inning'),
        ),
        migrations.AddField(
            model_name='inning',
            name='match_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score_card_match', to='cricketapp.MatchPlayerDetails'),
            preserve_default=False,
        ),
    ]
