# Generated by Django 2.0.5 on 2019-09-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0014_auto_20190925_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='club',
        ),
        migrations.RemoveField(
            model_name='scorerassignment',
            name='match',
        ),
        migrations.RemoveField(
            model_name='scorerassignment',
            name='scorer',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_team',
            new_name='team_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='team_2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='result',
            new_name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='batted_first',
        ),
        migrations.RemoveField(
            model_name='match',
            name='full_scorecard',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ground',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_won_by_team_id',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Ground',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Scorer',
        ),
        migrations.DeleteModel(
            name='ScorerAssignment',
        ),
    ]
