# Generated by Django 2.0.5 on 2019-09-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0015_auto_20190926_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=1, upload_to='image_logo/'),
            preserve_default=False,
        ),
    ]
