# Generated by Django 2.0.5 on 2019-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0016_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscorecard',
            name='man_of_match',
        ),
        migrations.RemoveField(
            model_name='playerscorecard',
            name='meadan_over',
        ),
        migrations.RemoveField(
            model_name='playerscorecard',
            name='over',
        ),
        migrations.RemoveField(
            model_name='playerscorecard',
            name='wicket',
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
