# Generated by Django 2.0.5 on 2019-09-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0017_auto_20190926_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inning',
            name='point',
        ),
        migrations.AlterField(
            model_name='inning',
            name='match_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_detail', to='cricketapp.MatchPlayerDetails'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
