# Generated by Django 2.0.5 on 2019-09-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0019_auto_20190928_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
